# Generated by Django 5.0.6 on 2024-05-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=400)),
                ('criacao', models.DateField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('urgnete', 'Urgente'), ('importante', 'Importante'), ('precisa ser feito', 'Precissa ser feito')], default='importante', max_length=25)),
                ('status', models.CharField(choices=[('concluido', 'Conluido'), ('pendente', 'Pendente'), ('adiado', 'Adiado')], default='pendente', max_length=25)),
            ],
        ),
    ]
