# Generated by Django 5.0.6 on 2024-05-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='categoria',
            field=models.CharField(choices=[('urgnete', 'Urgente'), ('importante', 'Importante'), ('precisa ser feito', 'Precisa ser feito')], default='importante', max_length=25),
        ),
    ]
